### ISSUE TITLE
Sentence graph doesn't work anymore

### ISSUE THREAD

**Issue by vnordin** [IBM-Bluemix/real-time-tone-analysis#28]
The "sentence" graph has stopped work. Document graph still works though. 
Probably the Tone Analyzer API have changed, so it might be good to check that.

**Comment by JakePeyser** [comment]
After debugging looks like the returned value of the `social` traits object that is returned from the Tone Analyzer API has changed from `neuroticism_big5` to `emotional_range_big5`. Need to make this slight change, as well as update the way we are creating swatch labels in the `addControl` function since this syntax breaks the current implementation.

**Comment by JakePeyser** [comment]
Also, the `writing` traits have now changed to `language` traits
