### ISSUE TITLE
only spanish record is not working

### ISSUE THREAD

**Issue by johnfelipe** [IBM-Bluemix/real-time-tone-analysis#30]
http://181.135.63.86:6001/

	sudo nano /home/felipe/speech-to-text-nodejs/src/data/models.json

	###
	{
	   "models": [
		  {
			 "url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/es-ES_BroadbandModel", 
			 "rate": 16000, 
			 "name": "es-ES_BroadbandModel", 
			 "language": "es-ES", 
			 "description": "Spanish broadband model."
		  }, 
		  {
			 "url": "https://stream.watsonplatform.net/speech-to-text/api/v1/models/es-ES_NarrowbandModel", 
			 "rate": 8000, 
			 "name": "es-ES_NarrowbandModel", 
			 "language": "es-ES", 
			 "description": "Spanish narrowband model."
		  }
	   ]
	}

	###

`npm run build`

but is not recording in spanish

Pls help me for fix this issue

**Comment by JakePeyser** [comment]
There are a few places that need to be updated when you change the Speech to Text broadband model to a different language. Start off by checking out the hidden dropdown in the [index.html file](https://github.com/IBM-Bluemix/real-time-tone-analysis/blob/master/public/index.html).

That being said, we are not currently supporting languages other than English in this demo since the [Tone Analyzer service currently only supports English](http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/tone-analyzer/index.shtml#language). If this changes and you would like to see multi-language support implemented, please file a request for enhancement on this repo!

**Comment by johnfelipe** [comment]
pls tell me when do u realese spanish support?

**Comment by johnfelipe** [comment]
hi, again, spanish support not installed yet?
